version: '3'
services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
  app:
    build: .
    environment:
      VK_TOKEN: "${VK_TOKEN}"
      REDIS_HOST : 0.0.0.0
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USER: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - "db:db"
    ports:
      - "8080:8080"
    depends_on:
      - db