/*
 * This file is generated by jOOQ.
*/
package com.vk.queuebot.domain.db;


import com.vk.queuebot.domain.db.tables.Queue;
import com.vk.queuebot.domain.db.tables.SchemaVersion;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.QUEUE</code>.
     */
    public static final Queue QUEUE = com.vk.queuebot.domain.db.tables.Queue.QUEUE;

    /**
     * The table <code>PUBLIC.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.vk.queuebot.domain.db.tables.SchemaVersion.SCHEMA_VERSION;
}
